name: woodlanders-launcher
base: core24
version: 0.1.2
summary: Woodlanders game launcher and updater
description: |
  Desktop launcher for the Woodlanders Single and Multiplayer Adventure game. It checks GitHub for the
  latest client release, downloads it into ${HOME}/.config/woodlanders/, and
  launches the game with a single button.

grade: stable
confinement: strict
icon: snap/gui/woodlanders-launcher.png

title: Woodlanders Launcher
license: MIT
contact: https://github.com/gcclinux/woodlanders/discussions
website: https://gcclinux.github.io/woodlanders/
source-code: https://github.com/gcclinux/woodlanders-launcher
issues: https://github.com/gcclinux/woodlanders/issues
donation: https://www.buymeacoffee.com/gcclinux

environment:
  JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-amd64
  PATH: $JAVA_HOME/bin:$PATH
  ALSA_CONFIG_PATH: $SNAP/etc/alsa.conf
  LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio:$LD_LIBRARY_PATH

apps:
  woodlanders-launcher:
    command: bin/app
    desktop: meta/gui/woodlanders-launcher.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - network
      - network-bind
      - opengl
      - audio-playback
      - pulseaudio

plugs:
  pulseaudio:
    interface: pulseaudio

parts:
  alsa-config:
    plugin: nil
    after: [launcher]
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/etc
      cat > $CRAFT_PART_INSTALL/etc/alsa.conf << 'EOF'
      pcm.!default {
        type pulse
      }
      ctl.!default {
        type pulse
      }
      EOF

  launcher:
    plugin: nil
    source: .
    build-packages:
      - openjdk-21-jdk
    stage-packages:
      - openjdk-21-jre
      - libgtk-3-0
      - libglib2.0-0
      - libasound2
      - libasound2-plugins
      - libpulse0
      - pulseaudio-utils
      - libx11-6
      - libxtst6
      - libnss3
      - openjfx
    override-build: |
      ./gradlew :app:installDist
      install -d "$CRAFT_PART_INSTALL"
      cp -r app/build/install/app/* "$CRAFT_PART_INSTALL/"
      chmod +x "$CRAFT_PART_INSTALL/bin/app"
